FROM python:3.12-slim

# Instalar curl
RUN apt-get update && apt-get install -y curl
# 🔹 Evitar prompts interactivos en la instalación
ENV DEBIAN_FRONTEND=noninteractive

# 🔹 Configurar zona horaria por defecto (Bogotá)
ENV TZ=America/Bogota
# Copiar la aplicación
WORKDIR /home/app
COPY . /home/app

# Instalar dependencias Python
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Exponer el puerto
EXPOSE 5090


# Comando para ejecutar la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5090"]

# uvicorn main:app --host 0.0.0.0 --port 5070
